# Site settings
title: Automated Exploratory Data Analysis
email: Billy.Buchanan@fayette.kyschools.us
description: GitHub Pages site for the Stata package eda
baseurl: "/eda" # Name of the repository
url: "https://wbuchanan.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  wbuchanan

# Build settings
markdown: kramdown
kramdown:
  input: GFM
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
